services:
  db:
    image: postgres:18-alpine
    container_name: prodmind_db
    environment:
      POSTGRES_USER: prodmind
      POSTGRES_PASSWORD: prodmind
      POSTGRES_DB: prodmind
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  adminer:
    image: adminer:latest
    container_name: prodmind_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
volumes:
  db_data:
